irregulares = open(r'Textos\verbos_irregulares_infinitivos.txt', 'r', encoding='UTF-8')
verbos_irregulares = {x for x in irregulares}
irregulares.close()

def extraer_infinitivos(path):
    '''Extrae verbos regulares.'''
    ret = []
    f = open(path, 'r+', encoding='UTF-8')
    for p in f:
        if p.endswith('ar\n') or p.endswith('er\n') or p.endswith('ir\n'):
            if p not in verbos_irregulares:
                ret.append(p.strip())
    return ret

def conjugar(verbo):
    # Ejemplo: x = 'amar\n', len(x) = 5, x[:len(x)] = 'amar', x[:len(x)-2] = 'am'
    conjugaciones = [verbo]
    n = len(verbo)
    if verbo.endswith('ar'):
        conjugaciones.append(verbo[:n-2]+'ado')
        conjugaciones.append(verbo[:n-2]+'ando')
        conjugaciones.append(verbo[:n-2]+'o')
        conjugaciones.append(verbo[:n-2]+'aba')
        conjugaciones.append(verbo[:n-2]+'é')
        conjugaciones.append(verbo[:n-2]+'as')
        conjugaciones.append(verbo[:n-2]+'ás')
        conjugaciones.append(verbo[:n-2]+'abas')
        conjugaciones.append(verbo[:n-2]+'aste')
        conjugaciones.append(verbo[:n-2]+'a')
        conjugaciones.append(verbo[:n-2]+'ó')
        conjugaciones.append(verbo[:n-2]+'amos')
        conjugaciones.append(verbo[:n-2]+'ábamos')
        conjugaciones.append(verbo[:n-2]+'áis')
        conjugaciones.append(verbo[:n-2]+'abais')
        conjugaciones.append(verbo[:n-2]+'asteis')
        conjugaciones.append(verbo[:n-2]+'an')
        conjugaciones.append(verbo[:n-2]+'aban')
        conjugaciones.append(verbo[:n-2]+'aron')
        conjugaciones.append(verbo[:n-2]+'aré')
        conjugaciones.append(verbo[:n-2]+'aría')
        conjugaciones.append(verbo[:n-2]+'arás')
        conjugaciones.append(verbo[:n-2]+'arías')
        conjugaciones.append(verbo[:n-2]+'ará')
        conjugaciones.append(verbo[:n-2]+'aremos')
        conjugaciones.append(verbo[:n-2]+'aríamos')
        conjugaciones.append(verbo[:n-2]+'aréis')
        conjugaciones.append(verbo[:n-2]+'aríais')
        conjugaciones.append(verbo[:n-2]+'arán')
        conjugaciones.append(verbo[:n-2]+'arían')
        conjugaciones.append(verbo[:n-2]+'e')
        conjugaciones.append(verbo[:n-2]+'ara')
        conjugaciones.append(verbo[:n-2]+'ase')
        conjugaciones.append(verbo[:n-2]+'are')
        conjugaciones.append(verbo[:n-2]+'es')
        conjugaciones.append(verbo[:n-2]+'aras')
        conjugaciones.append(verbo[:n-2]+'ases')
        conjugaciones.append(verbo[:n-2]+'ares')
        conjugaciones.append(verbo[:n-2]+'emos')
        conjugaciones.append(verbo[:n-2]+'áramos')
        conjugaciones.append(verbo[:n-2]+'ásemos')
        conjugaciones.append(verbo[:n-2]+'áremos')
        conjugaciones.append(verbo[:n-2]+'éis')
        conjugaciones.append(verbo[:n-2]+'arais')
        conjugaciones.append(verbo[:n-2]+'aseis')
        conjugaciones.append(verbo[:n-2]+'areis')
        conjugaciones.append(verbo[:n-2]+'en')
        conjugaciones.append(verbo[:n-2]+'aran')
        conjugaciones.append(verbo[:n-2]+'asen')
        conjugaciones.append(verbo[:n-2]+'aren')
        conjugaciones.append(verbo[:n-2]+'á')
        conjugaciones.append(verbo[:n-2]+'ad')
    elif verbo.endswith('er'):
        conjugaciones.append(verbo[:n-2]+'ido')
        conjugaciones.append(verbo[:n-2]+'iendo')
        conjugaciones.append(verbo[:n-2]+'o')
        conjugaciones.append(verbo[:n-2]+'ía')
        conjugaciones.append(verbo[:n-2]+'í')
        conjugaciones.append(verbo[:n-2]+'es')
        conjugaciones.append(verbo[:n-2]+'és')
        conjugaciones.append(verbo[:n-2]+'ías')
        conjugaciones.append(verbo[:n-2]+'iste')
        conjugaciones.append(verbo[:n-2]+'e')
        conjugaciones.append(verbo[:n-2]+'ío')
        conjugaciones.append(verbo[:n-2]+'emos')
        conjugaciones.append(verbo[:n-2]+'íabamos')
        conjugaciones.append(verbo[:n-2]+'imos')
        conjugaciones.append(verbo[:n-2]+'éis')
        conjugaciones.append(verbo[:n-2]+'íais')
        conjugaciones.append(verbo[:n-2]+'isteis')
        conjugaciones.append(verbo[:n-2]+'en')
        conjugaciones.append(verbo[:n-2]+'ieron')
        conjugaciones.append(verbo[:n-2]+'eré')
        conjugaciones.append(verbo[:n-2]+'ería')
        conjugaciones.append(verbo[:n-2]+'erás')
        conjugaciones.append(verbo[:n-2]+'erías')
        conjugaciones.append(verbo[:n-2]+'erá')
        conjugaciones.append(verbo[:n-2]+'eremos')
        conjugaciones.append(verbo[:n-2]+'eríamos')
        conjugaciones.append(verbo[:n-2]+'eréis')
        conjugaciones.append(verbo[:n-2]+'eríais')
        conjugaciones.append(verbo[:n-2]+'erán')
        conjugaciones.append(verbo[:n-2]+'erían')
        conjugaciones.append(verbo[:n-2]+'a')
        conjugaciones.append(verbo[:n-2]+'iera')
        conjugaciones.append(verbo[:n-2]+'iese')
        conjugaciones.append(verbo[:n-2]+'iere')
        conjugaciones.append(verbo[:n-2]+'as')
        conjugaciones.append(verbo[:n-2]+'ieras')
        conjugaciones.append(verbo[:n-2]+'ieses')
        conjugaciones.append(verbo[:n-2]+'ieres')
        conjugaciones.append(verbo[:n-2]+'amos')
        conjugaciones.append(verbo[:n-2]+'iéramos')
        conjugaciones.append(verbo[:n-2]+'iésemos')
        conjugaciones.append(verbo[:n-2]+'iéremos')
        conjugaciones.append(verbo[:n-2]+'áis')
        conjugaciones.append(verbo[:n-2]+'ierais')
        conjugaciones.append(verbo[:n-2]+'ieseis')
        conjugaciones.append(verbo[:n-2]+'iereis')
        conjugaciones.append(verbo[:n-2]+'an')
        conjugaciones.append(verbo[:n-2]+'ieran')
        conjugaciones.append(verbo[:n-2]+'iesen')
        conjugaciones.append(verbo[:n-2]+'ieren')
        conjugaciones.append(verbo[:n-2]+'é')
        conjugaciones.append(verbo[:n-2]+'ed')
    elif verbo.endswith('ir'):
        conjugaciones.append(verbo[:n-2]+'ido')
        conjugaciones.append(verbo[:n-2]+'iendo')
        conjugaciones.append(verbo[:n-2]+'o')
        conjugaciones.append(verbo[:n-2]+'ía')
        conjugaciones.append(verbo[:n-2]+'í')
        conjugaciones.append(verbo[:n-2]+'es')
        conjugaciones.append(verbo[:n-2]+'ís')
        conjugaciones.append(verbo[:n-2]+'ías')
        conjugaciones.append(verbo[:n-2]+'iste')
        conjugaciones.append(verbo[:n-2]+'e')
        conjugaciones.append(verbo[:n-2]+'ió')
        conjugaciones.append(verbo[:n-2]+'imos')
        conjugaciones.append(verbo[:n-2]+'íamos')
        conjugaciones.append(verbo[:n-2]+'ís')
        conjugaciones.append(verbo[:n-2]+'íais')
        conjugaciones.append(verbo[:n-2]+'isteis')
        conjugaciones.append(verbo[:n-2]+'en')
        conjugaciones.append(verbo[:n-2]+'ían')
        conjugaciones.append(verbo[:n-2]+'ieron')
        conjugaciones.append(verbo[:n-2]+'iré')
        conjugaciones.append(verbo[:n-2]+'iría')
        conjugaciones.append(verbo[:n-2]+'irás')
        conjugaciones.append(verbo[:n-2]+'irías')
        conjugaciones.append(verbo[:n-2]+'irá')
        conjugaciones.append(verbo[:n-2]+'iremos')
        conjugaciones.append(verbo[:n-2]+'iríamos')
        conjugaciones.append(verbo[:n-2]+'iréis')
        conjugaciones.append(verbo[:n-2]+'iríais')
        conjugaciones.append(verbo[:n-2]+'irán')
        conjugaciones.append(verbo[:n-2]+'irían')
        conjugaciones.append(verbo[:n-2]+'a')
        conjugaciones.append(verbo[:n-2]+'iera')
        conjugaciones.append(verbo[:n-2]+'iese')
        conjugaciones.append(verbo[:n-2]+'iere')
        conjugaciones.append(verbo[:n-2]+'as')
        conjugaciones.append(verbo[:n-2]+'ieras')
        conjugaciones.append(verbo[:n-2]+'ieses')
        conjugaciones.append(verbo[:n-2]+'ieres')
        conjugaciones.append(verbo[:n-2]+'amos')
        conjugaciones.append(verbo[:n-2]+'iéramos')
        conjugaciones.append(verbo[:n-2]+'iésemos')
        conjugaciones.append(verbo[:n-2]+'iéremos')
        conjugaciones.append(verbo[:n-2]+'áis')
        conjugaciones.append(verbo[:n-2]+'ierais')
        conjugaciones.append(verbo[:n-2]+'ieseis')
        conjugaciones.append(verbo[:n-2]+'iereis')
        conjugaciones.append(verbo[:n-2]+'an')
        conjugaciones.append(verbo[:n-2]+'ieran')
        conjugaciones.append(verbo[:n-2]+'iesen')
        conjugaciones.append(verbo[:n-2]+'ieren')
        conjugaciones.append(verbo[:n-2]+'id')
        conjugaciones.append(verbo[:n-2]+'an')
    return conjugaciones

def conjugar_verbos(lista_infinitivos):
    '''Conjuga una lista de verbos infinitivos regulares.'''
    ret = []
    for v in lista_infinitivos:
        ret.extend(conjugar(v))
    return ret

def generar():
    '''Genera un archivo con las conjugaciones de todos los verbos encontrados en el archivo cuya ruta es *path*.'''
    print('Generando conjugaciones...')
    print('Extrayendo infinitivos regulares...')
    verbos = extraer_infinitivos(r'Textos\palabras.txt')
    f = open(r'Textos\verbos_regulares_infinitivos.txt', 'w+', encoding='UTF-8')
    print('Guardando archivo de infinitivos regulares...')
    for v in verbos:
        print(v, file=f)
    f.close()
    print('Conjugando infinitivos regulares...')
    conjugaciones = conjugar_verbos(verbos)
    f = open(r'Textos\verbos_regulares_conjugados.txt', 'w+', encoding='UTF-8')
    print('Guardando archivo de regulares conjugados...')
    for c in conjugaciones:
        print(c, file=f)
    f.close()
    print(f'Se conjugaron {len(verbos)} verbos.')
    print(f'Se generaron {len(conjugaciones)} formas conjugadas.')